/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CspReportRouteImport } from './routes/csp-report'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SobreIndexRouteImport } from './routes/sobre/index'
import { Route as PublicacoesIndexRouteImport } from './routes/publicacoes/index'
import { Route as ProjectosIndexRouteImport } from './routes/projectos/index'
import { Route as ProducaoIndexRouteImport } from './routes/producao/index'
import { Route as PesquisaIndexRouteImport } from './routes/pesquisa/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias/index'
import { Route as LojaIndexRouteImport } from './routes/loja/index'
import { Route as ContactosIndexRouteImport } from './routes/contactos/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CarrinhoIndexRouteImport } from './routes/carrinho/index'
import { Route as AutoresIndexRouteImport } from './routes/autores/index'
import { Route as PublicacoesSlugRouteImport } from './routes/publicacoes/$slug'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido/$orderId'
import { Route as NoticiasSlugRouteImport } from './routes/noticias/$slug'
import { Route as NewsletterVerifyRouteImport } from './routes/newsletter/verify'
import { Route as LivroBookIdRouteImport } from './routes/livro/$bookId'
import { Route as AutorAuthorIdRouteImport } from './routes/autor/$authorId'
import { Route as AuthBridgeRouteImport } from './routes/auth/bridge'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CspReportRoute = CspReportRouteImport.update({
  id: '/csp-report',
  path: '/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreIndexRoute = SobreIndexRouteImport.update({
  id: '/sobre/',
  path: '/sobre/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesIndexRoute = PublicacoesIndexRouteImport.update({
  id: '/publicacoes/',
  path: '/publicacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectosIndexRoute = ProjectosIndexRouteImport.update({
  id: '/projectos/',
  path: '/projectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoIndexRoute = ProducaoIndexRouteImport.update({
  id: '/producao/',
  path: '/producao/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaIndexRoute = PesquisaIndexRouteImport.update({
  id: '/pesquisa/',
  path: '/pesquisa/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIndexRoute = ContactosIndexRouteImport.update({
  id: '/contactos/',
  path: '/contactos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoIndexRoute = CarrinhoIndexRouteImport.update({
  id: '/carrinho/',
  path: '/carrinho/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoresIndexRoute = AutoresIndexRouteImport.update({
  id: '/autores/',
  path: '/autores/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesSlugRoute = PublicacoesSlugRouteImport.update({
  id: '/publicacoes/$slug',
  path: '/publicacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterVerifyRoute = NewsletterVerifyRouteImport.update({
  id: '/newsletter/verify',
  path: '/newsletter/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroBookIdRoute = LivroBookIdRouteImport.update({
  id: '/livro/$bookId',
  path: '/livro/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorAuthorIdRoute = AutorAuthorIdRouteImport.update({
  id: '/autor/$authorId',
  path: '/autor/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/autor/$authorId': typeof AutorAuthorIdRoute
  '/livro/$bookId': typeof LivroBookIdRoute
  '/newsletter/verify': typeof NewsletterVerifyRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/publicacoes/$slug': typeof PublicacoesSlugRoute
  '/autores': typeof AutoresIndexRoute
  '/carrinho': typeof CarrinhoIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/contactos': typeof ContactosIndexRoute
  '/loja': typeof LojaIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/pesquisa': typeof PesquisaIndexRoute
  '/producao': typeof ProducaoIndexRoute
  '/projectos': typeof ProjectosIndexRoute
  '/publicacoes': typeof PublicacoesIndexRoute
  '/sobre': typeof SobreIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/autor/$authorId': typeof AutorAuthorIdRoute
  '/livro/$bookId': typeof LivroBookIdRoute
  '/newsletter/verify': typeof NewsletterVerifyRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/publicacoes/$slug': typeof PublicacoesSlugRoute
  '/autores': typeof AutoresIndexRoute
  '/carrinho': typeof CarrinhoIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/contactos': typeof ContactosIndexRoute
  '/loja': typeof LojaIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/pesquisa': typeof PesquisaIndexRoute
  '/producao': typeof ProducaoIndexRoute
  '/projectos': typeof ProjectosIndexRoute
  '/publicacoes': typeof PublicacoesIndexRoute
  '/sobre': typeof SobreIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/autor/$authorId': typeof AutorAuthorIdRoute
  '/livro/$bookId': typeof LivroBookIdRoute
  '/newsletter/verify': typeof NewsletterVerifyRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/publicacoes/$slug': typeof PublicacoesSlugRoute
  '/autores/': typeof AutoresIndexRoute
  '/carrinho/': typeof CarrinhoIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/contactos/': typeof ContactosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/pesquisa/': typeof PesquisaIndexRoute
  '/producao/': typeof ProducaoIndexRoute
  '/projectos/': typeof ProjectosIndexRoute
  '/publicacoes/': typeof PublicacoesIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/csp-report'
    | '/sitemap.xml'
    | '/auth/bridge'
    | '/autor/$authorId'
    | '/livro/$bookId'
    | '/newsletter/verify'
    | '/noticias/$slug'
    | '/pedido/$orderId'
    | '/publicacoes/$slug'
    | '/autores'
    | '/carrinho'
    | '/checkout'
    | '/contactos'
    | '/loja'
    | '/noticias'
    | '/pesquisa'
    | '/producao'
    | '/projectos'
    | '/publicacoes'
    | '/sobre'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/csp-report'
    | '/sitemap.xml'
    | '/auth/bridge'
    | '/autor/$authorId'
    | '/livro/$bookId'
    | '/newsletter/verify'
    | '/noticias/$slug'
    | '/pedido/$orderId'
    | '/publicacoes/$slug'
    | '/autores'
    | '/carrinho'
    | '/checkout'
    | '/contactos'
    | '/loja'
    | '/noticias'
    | '/pesquisa'
    | '/producao'
    | '/projectos'
    | '/publicacoes'
    | '/sobre'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/csp-report'
    | '/sitemap.xml'
    | '/auth/bridge'
    | '/autor/$authorId'
    | '/livro/$bookId'
    | '/newsletter/verify'
    | '/noticias/$slug'
    | '/pedido/$orderId'
    | '/publicacoes/$slug'
    | '/autores/'
    | '/carrinho/'
    | '/checkout/'
    | '/contactos/'
    | '/loja/'
    | '/noticias/'
    | '/pesquisa/'
    | '/producao/'
    | '/projectos/'
    | '/publicacoes/'
    | '/sobre/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CspReportRoute: typeof CspReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  AutorAuthorIdRoute: typeof AutorAuthorIdRoute
  LivroBookIdRoute: typeof LivroBookIdRoute
  NewsletterVerifyRoute: typeof NewsletterVerifyRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  PublicacoesSlugRoute: typeof PublicacoesSlugRoute
  AutoresIndexRoute: typeof AutoresIndexRoute
  CarrinhoIndexRoute: typeof CarrinhoIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ContactosIndexRoute: typeof ContactosIndexRoute
  LojaIndexRoute: typeof LojaIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  PesquisaIndexRoute: typeof PesquisaIndexRoute
  ProducaoIndexRoute: typeof ProducaoIndexRoute
  ProjectosIndexRoute: typeof ProjectosIndexRoute
  PublicacoesIndexRoute: typeof PublicacoesIndexRoute
  SobreIndexRoute: typeof SobreIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp-report': {
      id: '/csp-report'
      path: '/csp-report'
      fullPath: '/csp-report'
      preLoaderRoute: typeof CspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/': {
      id: '/sobre/'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/': {
      id: '/publicacoes/'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projectos/': {
      id: '/projectos/'
      path: '/projectos'
      fullPath: '/projectos'
      preLoaderRoute: typeof ProjectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/': {
      id: '/producao/'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa/': {
      id: '/pesquisa/'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/': {
      id: '/contactos/'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho/': {
      id: '/carrinho/'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autores/': {
      id: '/autores/'
      path: '/autores'
      fullPath: '/autores'
      preLoaderRoute: typeof AutoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/$slug': {
      id: '/publicacoes/$slug'
      path: '/publicacoes/$slug'
      fullPath: '/publicacoes/$slug'
      preLoaderRoute: typeof PublicacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/verify': {
      id: '/newsletter/verify'
      path: '/newsletter/verify'
      fullPath: '/newsletter/verify'
      preLoaderRoute: typeof NewsletterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$bookId': {
      id: '/livro/$bookId'
      path: '/livro/$bookId'
      fullPath: '/livro/$bookId'
      preLoaderRoute: typeof LivroBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$authorId': {
      id: '/autor/$authorId'
      path: '/autor/$authorId'
      fullPath: '/autor/$authorId'
      preLoaderRoute: typeof AutorAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CspReportRoute: CspReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  AutorAuthorIdRoute: AutorAuthorIdRoute,
  LivroBookIdRoute: LivroBookIdRoute,
  NewsletterVerifyRoute: NewsletterVerifyRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  PublicacoesSlugRoute: PublicacoesSlugRoute,
  AutoresIndexRoute: AutoresIndexRoute,
  CarrinhoIndexRoute: CarrinhoIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ContactosIndexRoute: ContactosIndexRoute,
  LojaIndexRoute: LojaIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  PesquisaIndexRoute: PesquisaIndexRoute,
  ProducaoIndexRoute: ProducaoIndexRoute,
  ProjectosIndexRoute: ProjectosIndexRoute,
  PublicacoesIndexRoute: PublicacoesIndexRoute,
  SobreIndexRoute: SobreIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
