import { ChevronLeft, ChevronRight, X } from 'lucide-react'
import { tagPalette, tileGradients, tileLayouts, type GalleryItem, type LightboxState, type Project } from './productionData'

export function ProductionHero({ videoSrc, labels }: { videoSrc: string; labels: Record<string, string> }) {
  return <section className="relative overflow-hidden bg-[#151311] text-white"><div className="absolute inset-0" aria-hidden="true"><iframe title={labels.videoAlt} src={videoSrc} className="pointer-events-none absolute left-1/2 top-1/2 h-[56.25vw] w-[100vw] min-h-full min-w-[177.78vh] -translate-x-1/2 -translate-y-1/2" allow="autoplay; fullscreen; picture-in-picture" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-br from-[#151311]/85 via-[#151311]/70 to-[#151311]/90" /></div><div className="absolute -top-24 right-0 h-64 w-64 rounded-full bg-[#c07238]/30 blur-3xl" /><div className="absolute bottom-0 left-0 h-64 w-64 rounded-full bg-[#f3e2cf]/10 blur-3xl" /><div className="container relative mx-auto px-4 py-24 lg:px-15"><p className="text-xs uppercase tracking-[0.4em] text-white/70">{labels.eyebrow}</p><h1 className="mt-4 text-4xl font-semibold md:text-6xl">{labels.title}</h1><p className="mt-5 max-w-2xl text-base text-white/80 md:text-lg">{labels.subtitle}</p></div></section>
}

export function ProductionIntro({ label, title, body }: { label: string; title: string; body: string }) {
  return <section className="bg-white"><div className="container mx-auto px-4 py-16 lg:px-15"><div className="max-w-3xl space-y-4"><p className="text-xs uppercase tracking-[0.35em] text-[#7f6f63]">{label}</p><h2 className="text-3xl font-semibold md:text-4xl">{title}</h2><p className="text-sm text-[#5a514a] md:text-base">{body}</p></div></div></section>
}

export function ProductionProjectsGrid({ projects, videoSrc, onOpen, labels }: { projects: Project[]; videoSrc: string; onOpen: (items: GalleryItem[], index: number, title: string) => void; labels: Record<string, string> }) {
  return <section className="bg-white"><div className="container mx-auto px-4 py-20 lg:px-15"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-12 lg:auto-rows-[220px] lg:gap-7">{projects.map((project, index) => { const layout = tileLayouts[index % tileLayouts.length]; const coverImage = project.gallery?.find((item) => item.type === 'image') ?? null; const hasGallery = (project.gallery?.length ?? 0) > 0; const gradient = tileGradients[index % tileGradients.length]; const titleClass = layout.size === 'large' ? 'text-3xl md:text-4xl' : layout.size === 'medium' ? 'text-2xl md:text-3xl' : 'text-2xl'; const descriptionClass = layout.size === 'small' ? 'text-sm' : 'text-sm md:text-base'; return <button key={project.id} id={project.id} type="button" onClick={() => hasGallery && onOpen(project.gallery ?? [], 0, project.title)} disabled={!hasGallery} className={`group relative flex min-h-[260px] w-full flex-col overflow-hidden rounded-none text-left transition-transform duration-300 md:min-h-[320px] lg:min-h-[240px] ${layout.className} ${hasGallery ? 'cursor-pointer hover:-translate-y-1' : 'cursor-default'}`} aria-label={labels.open.replace('{title}', project.title)}>{project.id === 'cidade-nas-maos' ? <div className="absolute inset-0"><iframe title={labels.videoAlt} src={videoSrc} className="pointer-events-none absolute left-1/2 top-1/2 h-[140%] w-[140%] -translate-x-1/2 -translate-y-1/2" allow="autoplay; fullscreen; picture-in-picture" aria-hidden="true" loading="lazy" /></div> : coverImage ? <img src={coverImage.src} alt={coverImage.alt} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" loading="lazy" /> : <div className={`absolute inset-0 bg-gradient-to-br ${gradient}`} />}<div className="absolute inset-0 bg-gradient-to-b from-black/65 via-black/20 to-black/70" /><div className="relative z-10 flex h-full flex-col justify-between p-6 md:p-7 lg:p-8"><div className="space-y-3"><h3 className={`${titleClass} font-semibold text-white`}>{project.title}</h3><p className={`${descriptionClass} line-clamp-3 text-white/80`}>{project.description}</p></div><div className="flex flex-wrap gap-2 pt-6 text-[10px] uppercase tracking-[0.35em]">{project.meta.map((item, itemIndex) => <span key={item} className={`border border-white/20 px-3 py-1 ${tagPalette[(index + itemIndex) % tagPalette.length]}`}>{item}</span>)}{!hasGallery && <span className="border border-white/30 bg-white/70 px-3 py-1 text-black">{labels.comingSoon}</span>}</div></div>{hasGallery && <span className="absolute right-6 top-6 rounded-none bg-black/50 px-3 py-1 text-[10px] uppercase tracking-[0.3em] text-white/80">{labels.images.replace('{count}', String(project.gallery?.length ?? 0))}</span>}</button>})}</div></div></section>
}

export function ProductionLightbox({ lightbox, activeItem, onClose, onPrevious, onNext, labels }: { lightbox: LightboxState | null; activeItem: GalleryItem | null; onClose: () => void; onPrevious: () => void; onNext: () => void; labels: Record<string, string> }) {
  if (!lightbox || !activeItem) return null
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 px-4 py-6" role="dialog" aria-modal="true" onClick={onClose}><div className="relative w-full max-w-5xl" onClick={(event) => event.stopPropagation()}><button type="button" onClick={onClose} className="absolute -top-10 right-0 flex items-center gap-2 text-xs uppercase tracking-[0.3em] text-white/80 hover:text-white">{labels.close}<X className="h-4 w-4" /></button><div className="relative overflow-hidden bg-black">{activeItem.type === 'video' ? <div className="relative h-[70vh] w-full"><iframe key={activeItem.src} title={activeItem.alt} src={activeItem.src} className="absolute inset-0 h-full w-full" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen /></div> : <img src={activeItem.src} alt={activeItem.alt} className="h-[70vh] w-full object-contain" />}{lightbox.items.length > 1 && <><button type="button" onClick={onPrevious} className="absolute left-4 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center border border-white/40 bg-black/40 text-white transition hover:bg-black/60" aria-label={labels.previous}><ChevronLeft className="h-5 w-5" /></button><button type="button" onClick={onNext} className="absolute right-4 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center border border-white/40 bg-black/40 text-white transition hover:bg-black/60" aria-label={labels.next}><ChevronRight className="h-5 w-5" /></button></>}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs uppercase tracking-[0.35em] text-white/70"><span>{lightbox.title}</span><span>{lightbox.index + 1} / {lightbox.items.length}</span></div></div></div>
}
